{"name": "Переход на страницу восстановления пароля по кнопке Восстановить", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_recovery.TestRecoveryPage object at 0x00000146750D9070>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"89338f3f-5c4d-4cd8-8ec7-a8d20ce75425\")>\n\n    @allure.title('Переход на страницу восстановления пароля по кнопке Восстановить')\n    def test_cross_via_recovery_button(self, driver):\n        main_page = MainPage(driver)\n        main_page.open_main_page()\n        main_page.click_account_button()\n        login_page = LoginPage(driver)\n>       login_page.click_recover_password_button()\n\ntests\\test_recovery.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:38: in click_recover_password_button\n    self.wait_element(LoginPageLocators.RECOVER_PASSWORD_BUTTON)\npages\\base_page.py:30: in wait_element\n    return WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"89338f3f-5c4d-4cd8-8ec7-a8d20ce75425\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x000001467512D3A0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Открыть главную страницу Stellar Burgers", "status": "passed", "start": 1721671433281, "stop": 1721671433433}, {"name": "Клик на кнопку Личный кабинет", "status": "passed", "start": 1721671433433, "stop": 1721671433744}, {"name": "Нажать на кнопку Восстановить пароль", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Diana\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Diana\\PycharmProjects\\Diplom_3\\pages\\login_page.py\", line 38, in click_recover_password_button\n    self.wait_element(LoginPageLocators.RECOVER_PASSWORD_BUTTON)\n  File \"C:\\Users\\Diana\\PycharmProjects\\Diplom_3\\pages\\base_page.py\", line 30, in wait_element\n    return WebDriverWait(self.driver, 20).until(expected_conditions.visibility_of_element_located(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Diana\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1721671433744, "stop": 1721671453936}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1721671433281, "stop": 1721671453939, "uuid": "5302f798-25cb-4dc9-a023-af32366f87d7", "historyId": "62df7f9c3a45581298a0f72b73b4a43e", "testCaseId": "de9de81487bbf0978e2cd4d1ab3dbb28", "fullName": "tests.test_recovery.TestRecoveryPage#test_cross_via_recovery_button", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_recovery"}, {"name": "subSuite", "value": "TestRecoveryPage"}, {"name": "host", "value": "DESKTOP-02PLGO0"}, {"name": "thread", "value": "37560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_recovery"}]}